<?php

namespace Emova\IelraBundle\Repository;

/**
 * OrderLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;

class OrderLineRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllOrderLine($statut)
    {
        $query = $this->createQueryBuilder('o')
            ->where('o.statut > :statut')
            ->setParameter('statut', $statut)
            ->orderBy('o.dateFacturation', 'ASC')
            ->getQuery();

        $orders = $query->getResult();
        return $orders;
        // to get just one result:
        // $product = $query->setMaxResults(1)->getOneOrNullResult();
    }
}
